/*******************************************************************************
 * Module      : Ultrasonic
 *
 * File Name   : ultrasonic.c
 *
 * Description : Source file for the Ultra_sonic driver
 *
 * Author      : Mazen Khaled
 *******************************************************************************/

#include "gpio.h"
#include "ultrasonic.h"
#include "icu.h"
#include "util/delay.h"

uint8 g_edgeCount = 0;  /*Counting number of edges to find distance*/
uint16 g_timeHigh = 0;  /*time taken*/



/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*******************************************************************************
 * [Function Name] : Ultrasonic_init
 *
 * [Description]   : Initialize the ICU driver.
 *******************************************************************************/
void Ultrasonic_init(void){
	/*configuration of the ICU*/
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	/*call back function in the ICU driver*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/*configuration the ICU driver*/
	Icu_init(&Icu_Config);

	GPIO_setupPinDirection(TRIGGER_PORT,TRIGGER_PIN,PIN_OUTPUT);

	GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN,LOGIC_LOW);
}

/*******************************************************************************
 * [Function Name] : Ultrasonic_edgeProcessing
 *
 * [Description]   : It's used to calculate the high time generated by the
 * 					 ultrasonic sensor.
 *
 *******************************************************************************/
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*Clear the timer counter register*/
		Icu_clearTimerValue();
		/* Detect falling edge*/
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time*/
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		/*as here we only need to calculate pulse time between 2 edges*/
		g_edgeCount = 0;
	}

}

/*******************************************************************************
 * [Function Name] : Ultrasonic_Trigger
 *
 * [Description]   : Send a Trigger pulse
 *
 *******************************************************************************/
void Ultrasonic_Trigger(void){

	/*enabling trigger pin*/
	GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN,LOGIC_HIGH);
	_delay_us(10);
	/*disabling trigger pin after a little delay(10 micro sec)*/
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_LOW);

}

/*******************************************************************************
 * [Function Name] : Ultrasonic_readDistance
 *
 * [Description]   : Send the trigger pulse by using Ultrasonic_Trigger function.
 * 					 Start the measurements by the ICU from this moment and returning
 * 					 the measured distance.
 *
 *******************************************************************************/
uint16 Ultrasonic_readDistance(void){

	static uint16 distance;
	/*calibration*/
	static uint16 distance_calibration;
	/*enabling triggering*/
	Ultrasonic_Trigger();

	distance = g_timeHigh*0.01715+1; /* equation to get the distance*/

	if(distance>=342){
		distance_calibration=distance+2;
		return distance_calibration;
	}
	else if(distance>=154){
		distance_calibration=distance+1;
		return distance_calibration;
	}

	else{
	return distance;}

	return 1;
}
